version: '3.5'
services:
  ffmpeg:
    image: ffmpeg-rockchip:arm64
    container_name: ffmpeg
    restart: always
    privileged: true
    cap_add:
      - SYS_ADMIN
    volumes:
     - ./test:/tmp/test
    ports:
      - 8080:80
      - 1935:1935
    devices:
     - /dev/snd:/dev/snd
     - /dev/video0:/dev/video0
     #- /dev/video-enc0:/dev/video-enc0
     #- /dev/video-dec0:/dev/video-dec0
     - /dev/rga:/dev/rga
     - /dev/dri:/dev/dri
     - /dev/dma_heap:/dev/dma_heap
     - /dev/mpp_service:/dev/mpp_service
     - /dev/rk_cec:/dev/rk_cec      
    networks:
      docker:
    logging:
      options:
        max-size: 100M
    
networks:
  docker:    